"""empty message

Revision ID: 561457464ad8
Revises: 340d065c40dc
Create Date: 2022-07-10 11:16:19.244684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561457464ad8'
down_revision = '340d065c40dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_booked_slots_event_id'), 'booked_slots', ['event_id'], unique=False)
    op.create_index(op.f('ix_doctor_user_id'), 'doctor', ['user_id'], unique=False)
    op.create_index(op.f('ix_event_slot_id'), 'event', ['slot_id'], unique=False)
    op.create_index(op.f('ix_event_meta_event_id'), 'event_meta', ['event_id'], unique=False)
    op.create_index(op.f('ix_patient_gender'), 'patient', ['gender'], unique=False)
    op.create_index(op.f('ix_patient_name'), 'patient', ['name'], unique=False)
    op.create_index(op.f('ix_patient_user_id'), 'patient', ['user_id'], unique=False)
    op.create_index(op.f('ix_rating_doctor_id'), 'rating', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_rating_patient_id'), 'rating', ['patient_id'], unique=False)
    op.create_index(op.f('ix_slot_day_id'), 'slot', ['day_id'], unique=False)
    op.create_index(op.f('ix_slot_doctor_id'), 'slot', ['doctor_id'], unique=False)
    op.create_index('idx_user_name', 'user', ['name'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_name', table_name='user', postgresql_using='gin')
    op.drop_index(op.f('ix_slot_doctor_id'), table_name='slot')
    op.drop_index(op.f('ix_slot_day_id'), table_name='slot')
    op.drop_index(op.f('ix_rating_patient_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_doctor_id'), table_name='rating')
    op.drop_index(op.f('ix_patient_user_id'), table_name='patient')
    op.drop_index(op.f('ix_patient_name'), table_name='patient')
    op.drop_index(op.f('ix_patient_gender'), table_name='patient')
    op.drop_index(op.f('ix_event_meta_event_id'), table_name='event_meta')
    op.drop_index(op.f('ix_event_slot_id'), table_name='event')
    op.drop_index(op.f('ix_doctor_user_id'), table_name='doctor')
    op.drop_index(op.f('ix_booked_slots_event_id'), table_name='booked_slots')
    # ### end Alembic commands ###
