"""empty message

Revision ID: 97247c99511d
Revises: 8140c88ea8e8
Create Date: 2022-07-03 18:56:37.513899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97247c99511d'
down_revision = '8140c88ea8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('image', sa.String(length=32), nullable=True))
    op.alter_column('doctor', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('doctor', 'image')
    # ### end Alembic commands ###
