"""empty message

Revision ID: e6f51c35e414
Revises: 87a8876da2c2
Create Date: 2022-07-04 00:56:17.396569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f51c35e414'
down_revision = '87a8876da2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    op.drop_column('user', 'dob')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('gender', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
