"""empty message

Revision ID: f5a07e465f78
Revises: f53bcae998bf
Create Date: 2022-07-03 19:38:36.410483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a07e465f78'
down_revision = 'f53bcae998bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'image')
    # ### end Alembic commands ###
